# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54cb921800d165bf5ea580e282a05f0368b14dff703e6b624f6237dd5d2c9b686e0bb6c6bb122d45f3b1f0b6baac84d4dcf04bf019e9e000aaeb49bb8b93f488

test:
  secret_key_base: 3dc8fea8e3373e0836e9ea238137644e2dea52754edc97f094a613bea880243f70e64b91b7c90a761969ec33c3c6b1b7462f5847194b9be828e2dd7807d4136d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
